image: softescu/centos:node12
stages:
  - BUILD-testing

BUILD-testing:
  stage: BUILD-testing
  tags:
    - docker-runner
  except:
    - /^cherry-pick*/
    - /^revert*/
    - /^demo*/
  variables:
    BUILD_DIRECTORY: $CI_PROJECT_DIR
  script:
    - cd omn
    - ls
    - npm install
    - ng lint
    - npm run-script build
