export enum EmailValidateModes {
  EMAIL_CHANGE_VALIDATE,
  EMAIL_NEW_VALIDATE,
  EMAIL_CHANGE_VALIDATE_SUCCESS,
  EMAIL_NEW_VALIDATE_SUCCESS,
  EMAIL_CODE_PROCESSING,
  EMAIL_CODE_CHANGE_PROCESSING,
}
