import { Component, OnInit, HostBinding } from '@angular/core';

@Component({
  selector: 'app-insurance-conditions',
  templateUrl: './insurance-conditions.component.html',
  styleUrls: ['./insurance-conditions.component.scss'],
})
export class InsuranceConditionsComponent implements OnInit {
  @HostBinding('class') color = 'ion-color-white-page';
  conditions = [
    `1. CLAUZA OPERATIVĂ`,
    `1.1. OMNIASIG VIENNA INSURANCE GROUP se obligă ca, în urma producerii sau apariţiei oricărui eveniment asigurat, în baza informaţiilor furnizate de Asigurat / Contractant, precum şi a oricăror date privind riscurile asigurate transmise în scris de acesta, sub rezerva respectării întocmai a condiţiilor, excluderilor şi clauzelor stabilite de comun acord şi în baza plăţii primei de asigurare în cuantumul şi la scadenţele prevăzute în Poliţă, să plătească Asiguratului sau, după caz, Beneficiarului despăgubirea cuvenită în cuantumul şi în condiţiile prevăzute în prezenta Poliţă.`,
    `2. DEFINIŢII ŞI INTERPRETĂRI`,
    `În tot cuprinsul acestei Poliţe termenii de mai jos au numai înţelesul atribuit prin următoarele definiţii:`,
    `2.1. Alunecare de teren: mişcare lină a terenului cauzată de mişcări tectonice sau de eroziune naturală.`,
    `Anexe: construcţii care nu sunt legate structural de locuinţă (boxă, garaj exterior, magazii, foişoare, grajduri, garduri de împrejmuire, porţi şi construcţii speciale de tipul: piscine, saune, fântâni arteziene, recipiente GPL, instalaţii solare, eoliene, rampe auto, alei, pavaje, grătar / cuptor exterior);`,
    `2.2. Apă de conductă:`,
    `- scurgeri accidentale de apă din ţevi de aducţie, derivaţie, evacuare sau canalizare, din alte instalaţii de alimentare cu apă sau de încălzire cu apă sau aburi, ca urmare a avariilor accidentale produse la aceste instalaţii aflate în incintele asigurate sau aflate în spaţiile învecinate aflate în clădirea în care se găsesc bunurile asigurate;`,
    `- scurgeri de apă provenită din spaţiile învecinate de locuit (care nu aparţin Asiguratului) aflate în clădirea în care se găsesc bunurile asigurate, din alte cauze decât avariile accidentale.`,
    `2.3. Asigurat: titularul interesului cu privire la bunul asigurat, respectiv persoana care poate suferi un prejudiciu patrimonial în situaţia în care bunul asigurat suferă o daună.`,
    `În cazul asigurării de răspundere civilă faţă de terţi, noţiunea de Asigurat se referă atât la proprietarul / locatarul locuinţei cât şi la persoanele care în mod statornic locuiesc împreună cu acesta şi/sau care au calitatea de soţ / soţie sau persoane pentru care răspunde conform legii.`,
    `2.4. Avalanşă de zăpadă: masă de zăpadă care se desprinde de pe coasta unui munte şi alunecă spre vale.`,
    `2.5. Beneficiar: persoana îndreptăţită să primească despăgubirea în caz de daună.`,
    `2.6. Boom sonic: acţiunea directă a presiunii generată de spargerea zidului sonic de către o aeronavă în zbor.`,
    `2.7. Bunuri conţinute: bunurile (altele decât cele care prin natura lor fac parte integrantă din construcţie) aparţinând Asiguratului sau persoanelor care în mod statornic locuiesc cu Asiguratul ori deţinute spre păstrare, folosinţă ori în grijă sau custodie de aceştia.`,
    `2.8. Caz fortuit: eveniment care nu poate fi prevăzut şi nici împiedicat de către cel care ar fi fost chemat să răspundă dacă evenimentul nu s-ar fi produs.`,
    `2.9. Cădere de corpuri aeriene: căderea accidentală de corpuri aeriene pe bunul asigurat. Se iau în considerare căderi de corpuri cum ar fi aeronave, părţi ale acestora ori meteoriţi. Nu se consideră cădere de corpuri aeriene căderea de părţi ale bunului asigurat şi nici căderea sau prăbuşirea unor corpuri terestre.`,
    `2.10. Centrală termică: instalaţie sau ansamblu de instalaţii destinate producerii agentului termic şi apei calde, care echipează locuinţa asigurată (instalaţii individuale sau de bloc / scară). Noţiunea de centrală termică cuprinde şi instalaţiile auxiliare ataşate (instalaţii pentru dedurizarea apei, arzătoare, boilere, schimbătoare de căldură, instalaţii de evacuare a gazelor arse).`,
    `2.11. Coliziune cu (auto)vehicule: impact nemijlocit al (auto)vehiculelor cu bunurile asigurate (clădiri şi/sau bunuri conţinute în locuinţă), aflate la adresa menţionată în Poliţă.`,
    `2.12. Contractant: persoana care încheie contractul de asigurare cu OMNIASIG VIENNA INSURANCE GROUP pentru şi în numele Asiguratului şi se obligă faţă de OMNIASIG VIENNA INSURANCE GROUP să plătească prima de asigurare precum şi să respecte obligaţiile care îi revin prin contract.`,
    `2.13. Culpă: vinovăţie, sub forma imprudenţei sau neglijenţei.`,
    `2.14. Culpa gravă: acţionarea cu neglijenţă sau imprudenţă pe care nici persoana cea mai lipsită de dibăcie nu ar fi manifestat-o faţă de propriile interese.`,
    `2.15. Cutremur: mişcare seismică bruscă a scoarţei terestre, orizontală, verticală sau de torsiune, datorată unui dezechilibru fizic produs în interiorul acesteia, având origine tectonică, vulcanică sau de prăbuşire.`,
    `2.16. Daună: prejudiciu material (avariere, distrugere, pierdere) provocat bunurilor asigurate de un eveniment asigurat, precizat în şi acoperit de asigurarea oferită de Poliţă.`,
    `2.17. Daună parţială: daună a bunului asigurat, astfel încât prin reparare, recondiţionare sau restaurare ori înlocuirea unor părţi componente, poate fi adus în starea în care se afla înaintea producerii sau apariţiei oricărui eveniment asigurat, costul aferent acestor operaţii fiind mai mic decât valoarea de asigurare.`,
    `2.18. Daună totală: daună a bunului asigurat într-un asemenea grad încât refacerea, repararea, înlocuirea, recondiţionarea sau restaurarea părţilor sau pieselor componente nu mai este posibilă ori costul acestora ar fi egal cu sau mai mare decât valoarea de asigurare.`,
    `2.19. Despăgubire cuvenită: suma datorată de OMNIASIG VIENNA INSURANCE GROUP Asiguratului sau Beneficiarului, după caz, urmare a producerii sau apariţiei oricărui eveniment asigurat.`,
    `2.20. Eveniment asigurat: risc asigurat care s-a produs sau începe să se manifeste în timpul perioadei de asigurare, cauzator de daune şi în urma căruia se naşte dreptul la despăgubire.`,
    `Se consideră unul şi acelaşi eveniment asigurat:`,
    `(i) seria de riscuri asigurate de acelaşi tip, produse în mod imprevizibil şi accidental şi acoperite de prezenta Poliţă, care apar sau încep să se manifeste în timpul perioadei de asigurare. Pentru anumite riscuri asigurate, definite în prezentele condiţii de asigurare, se consideră unul şi acelaşi eveniment asigurat seria de astfel de riscuri asigurate care apar sau încep să se manifeste într-un interval determinat, precizat în prezentele condiţii de asigurare, care începe în timpul perioadei de asigurare; niciun risc asigurat individual de acelaşi tip, produs în afara acestui interval nu va face parte din acelaşi eveniment asigurat;`,
    `(ii) mai multe riscuri asigurate de tipuri diferite precizate în şi acoperite de prezenta Poliţă, care concură la producerea uneia şi aceleiaşi daune.`,
    `2.21. Explozie: eliberare bruscă şi violentă de energie ca urmare a unei reacţii chimice sau fizice, însoţită de dezvoltare de lucru mecanic într-un timp foarte scurt.`,
    `2.22. Forţa majoră: situaţie invocată de una din părţi, dovedită cu documente emise de autorităţi publice competente şi cauzată de un eveniment extern, imprevizibil, absolut invincibil şi inevitabil care a împiedicat una din părţi să îşi îndeplinească obligaţiile contractuale.`,
    `2.23. Franşiză: partea din daună suportată de Asigurat, stabilită fie ca valoare fixă, fie ca procent din suma asigurată totală a bunului sau categoriei de bunuri ori din limita / sublimita de răspundere, fie ca procent din daună.`,
    `2.24. Furt prin efracţie: fapta unei persoane sau grup de persoane săvârşită prin violenţă, care poate fi probată cu dovezi materiale, de a-şi însuşi pe nedrept bunuri ale Asiguratului, prin folosirea următoarelor mijloace:`,
    `(i) intrarea / ieşirea în / din clădirea sau incinta (spaţiul) în care se află bunurile asigurate prin spargerea / distrugerea pereţilor, acoperişului, tavanelor, uşilor, ferestrelor, pardoselilor, împrejmuirilor / gardurilor, porţilor sau prin stricarea sau forţarea dispozitivelor de închidere, precum şi furtul urmat de întrebuinţarea unor astfel de mijloace pentru păstrarea bunului furat sau pentru înlăturarea urmelor infracţiunii, ori pentru ca făptuitorul să-şi asigure scăparea.`,
    `(ii) spargerea unui seif sau unui alt spaţiu închis din clădire.`,
    `2.25. Furtună: mişcare puternică a aerului produsă de o perturbaţie atmosferică violentă, în general însoţită de descărcări electrice.`,
    `2.26. Greutatea stratului de zăpadă sau de gheaţă: distrugere provocată de excesul de masă de zăpadă sau gheaţă acumulată pe acoperişuri sau care acţionează asupra elementelor de sprijin ale construcţiilor.`,
    `2.27. Grevă: încetarea organizată şi voluntară a activităţii unei părţi importante a angajaţilor unui angajator, în scopul de a impune revendicări de ordin economic, social sau politic.`,
    `2.28. Grindină: precipitaţie atmosferică conţinând particule de gheaţă.`,
    `2.29. Incendiu: ardere cu flacără deschisă (foc) care s-a produs în absenţa unei vetre destinate acestui scop sau a ieşit din vatră, având forţa de a se extinde prin propria sa putere. Arderea cu aport limitat de oxigen (arderea mocnită), precum şi efectul aplicării deliberate a focului sau căldurii ca parte a unui proces sau a unei operaţii nu se consideră incendiu. De asemenea, efectul căldurii într-un scurt-circuit la instalaţia electrică nu se consideră incendiu, decât dacă flăcările produse prin scurt-circuit se extind.`,
    `2.30. Inundaţie: acoperirea cu apă a unei porţiuni de uscat, ca urmare a:`,
    `(i) revărsării peste marginile cursurilor sau bazinelor de apă (lacuri, mare);`,
    `(ii) ruperii digurilor, barajelor sau malurilor;`,
    `(iii) îngustării bruşte şi neaşteptate a cursului apei;`,
    `(iv) precipitaţiilor atmosferice abundente sau topirii zăpezilor;`,
    `(v) apelor subterane care ies la suprafaţa pământului şi/sau a pardoselii clădirii asigurate sau în care se află bunuri asigurate.`,
    `2.33. Limita de răspundere: suma maximă care reprezintă răspunderea OMNIASIG VIENNA INSURANCE GROUP în legătură cu toate evenimentele produse în perioada de asigurare (reprezintă maximul despăgubirii care poate fi plătită) - în cazul asigurării de răspundere civilă faţă de terţi.`,
    `2.34. Locuinţa: ansamblu care cuprinde:`,
    `(i) Clădirea – construcţie locuită permanent sau temporar (casă, vilă sau apartament în bloc / vilă), alcătuită din una sau mai multe camere de locuit, cu destinaţie de locuinţă şi folosită în acest scop;`,
    `(ii) dependinţele, dotările, utilităţile şi amenajările interioare legate structural de clădirea / construcţia cu destinaţie de locuinţă;`,
    `(iii) instalaţiile fixe aflate la locaţia asigurată:`,
    `- instalaţia electrică fixă: conductoarele instalaţiei electrice (de iluminat, prize şi de curenţi slabi) îngropate sub tencuială, inclusiv prizele şi întrerupătoarele şi corpurile de iluminat tip plafonieră sau spot încorporate (excepţie: lustre, lămpi, abajure, aplice, fasunguri, becuri, tuburi de iluminat);`,
    `- instalaţiile sanitare (alimentare cu apă, canalizare inclusiv obiectele sanitare);`,
    `- instalaţia de încălzire, inclusiv conductele şi radiatoarele (calorifere), instalaţiile de gaze naturale (inclusiv centrala termică, hidroforul şi boilerul, panourile solare / fotovoltaice);`,
    `- instalaţii de ventilare şi climatizare (fără ventilatoarele electrice şi aparatele de aer condiţionat mobile);`,
    `- instalaţie de protecţie (paratrăsnet / împământare, alarmă incendiu, alarmă furt), antene radio / TV / satelit.`,
    `În limita sumei asigurate pentru clădirea cu destinaţie de locuinţă, se includ în această categorie şi părţile comune conform cotei indivize.`,
    `Terenul aferent locuinţei nu este asociat noţiunii de locuinţă şi nu face obiectul asigurării.`,
    `2.35. Obiecte de artă: bunuri semnificative prin valoarea lor artistică, documentară, istorică, ştiinţifică, tehnică, culturală şi memorialistică.`,
    `2.36. Pătare cu fum: deteriorarea produsă în mod direct de fumul cauzat de incendiu.`,
    `2.37. Perioada de asigurare: intervalul de timp menţionat în Poliţă în care pot apărea evenimente asigurate pentru care OMNIASIG VIENNA INSURANCE GROUP datorează despăgubiri în baza prezentei Poliţe.`,
    `2.38. Ploaie torenţială: căderea unei mari cantităţi de precipitaţii în timp scurt şi pe o suprafaţă limitată.`,
    `2.39. Poliţă: contract de asigurare (formă scrisă) cuprinzând Specificaţia, Condiţiile de asigurare, Oferta de asigurare (după caz), eventualele acte adiţionale şi orice alt document anexat.`,
    `2.40. Prăbuşire de corpuri terestre: prăbuşirea / căderea accidentală pe bunurile asigurate de corpuri străine, altele decât aeronave, părţi ale acestora şi meteoriţi, precum: stânci, pietre, copaci, elemente ale reţelelor de distribuţie sau de transmisie energie electrică, elemente de transport pe cablu (stâlpi, cabluri, ţevi etc), relee de transmisiuni, macarale sau elemente componente (inclusiv a obiectelor ridicate / manipulate de acestea), elemente de construcţie ale clădirilor învecinate (inclusiv instalaţiile aferente acestor clădiri) etc.`,
    `2.41. Prăbuşire de teren: surparea bruscă a unei suprafeţe de teren cauzată de mişcări tectonice sau de eroziune naturală.`,
    `2.42. Prima de asigurare: suma datorată de Asigurat / Contractant pentru preluarea în asigurare de către OMNIASIG VIENNA INSURANCE GROUP a riscurilor asigurate.`,
    `2.43. Rea-credinţă: acea atitudine a unei persoane care comite o faptă contrară legii sau contractului în care este parte, fiind conştientă de caracterul ilicit al conduitei sale.`,
    `2.44. Refulare: evacuarea în sens opus celui proiectat a apelor reziduale / pluviale prin conductele de evacuare / canalizare aparţinând locuinţei asigurate, ca urmare a obturării acestor conducte sau ca urmare a debitului foarte mare prin aceste conducte.`,
    `2.45. Revoltă: Demonstraţii violente ce duc la agitaţie, însoţite de acţiuni ilegale şi ostilitate la adresa autorităţilor cu scopul de a distruge echilibrul existent.`,
    `2.46. Risc asigurat: eveniment viitor, posibil dar incert, acoperit de OMNIASIG VIENNA INSURANCE GROUP a cărui producere ar putea cauza daune.`,
    `2.47. Sublimită: Sumă stabilită în cadrul sumei asigurate / limitei de răspundere pentru anumite evenimente şi/sau costuri / cheltuieli asigurate nominalizate în Poliţă care reprezintă maximul răspunderii OMNIASIG VIENNA INSURANCE GROUP în cazul producerii sau apariţiei evenimentului respectiv sau în cazul efectuării costurilor / cheltuielilor respective; sublimita nu operează în nici o situaţie în sensul majorării sumei asigurate / limitei de răspundere asumate de OMNIASIG VIENNA INSURANCE GROUP.`,
    `2.48. Sumă asigurată: valoarea menţionată în Poliţă pentru care s-a încheiat asigurarea; reprezintă maximul răspunderii OMNIASIG VIENNA INSURANCE GROUP în cazul producerii sau apariţiei unuia sau mai multor evenimente asigurate. Dacă părţile nu convin altfel prin menţiuni exprese în Poliţă, suma asigurată conţine TVA.`,
    `2.49. Tâlhăria: furtul săvârşit prin întrebuinţare de violenţe sau ameninţări, ori prin punerea victimei în stare de inconştienţă sau neputinţa de a se apăra precum şi furtul urmat de întrebuinţarea unor astfel de mijloace pentru păstrarea bunului furat sau pentru înlăturarea urmelor infracţiunii ori pentru ca făptuitorul să-şi asigure scăparea.`,
    `2.50. Tornadă: vârtej de vânt devastator cu arie restrânsă, adesea însoţit de ploi torenţiale.`,
    `2.51. Trăsnet: descărcare electrică luminoasă, având o durată de ordinul microsecundelor şi o intensitate a curentului de ordinul sutelor de mii de amperi, care se produce între un nor şi sol sau obiecte aflate pe sol. Daunele produse de trăsnet constau în transferul nemijlocit al efectului acestuia asupra bunului asigurat.`,
    `2.52. Tulburări civile: Demonstraţii violente care nu intră în categoria revoltelor, degenerând în agitaţii culminând cu frământări sociale şi acţiuni ilegale.`,
    `2.53. Uragan: vânt foarte puternic cu acţiune distrugătoare, însoţit adesea de ploi torenţiale.`,
    `2.54. Uzură: deprecierea calităţilor unui bun stabilită funcţie de vechime, întrebuinţare şi starea de întreţinere a acestuia.`,
    `2.55. Valoare de asigurare: valoarea corectă, intrinsecă, a unui bun la un moment dat, în funcţie de semnificaţia sa. Semnificaţia valorii de asigurare poate fi: valoarea reală, valoarea de înlocuire, valoarea de piaţă sau valoarea evaluată de un evaluator autorizat.`,
    `(i) Valoare de înlocuire: costul construirii, producerii sau achiziţionării bunului respectiv sau al unui bun similar din punct de vedere al parametrilor funcţionali şi constructivi, la preţurile uzuale de piaţă în care sunt incluse costurile de transport, de instalare, de punere în funcţiune, precum şi taxe şi comisioane vamale.`,
    `(ii) Valoarea de piaţă: suma estimată pentru care un bun ar putea fi schimbat, la data evaluării, între un cumpărător hotărât şi un vânzător hotărât, într-o tranzacţie nepărtinitoare, după o activitate de marketing adecvată şi în care părţile au acţionat fiecare în cunoştinţă de cauză, prudent şi fără constrângere.`,
    `(iii) Valoare reală: valoare de înlocuire (de nou) a bunului din care se scade uzura.`,
    `(iv) Valoarea evaluată de un evaluator autorizat: valoarea unui bun (clădire, construcţie) determinată de un evaluator autorizat în cazul în care bunul respectiv este cesionat către o instituţie creditoare. În cazul clădirilor, valoarea de asigurare (ca valoare evaluată de un evaluator autorizat) nu trebuie să conţină valoarea terenului.`,
  ];
  constructor() {}

  ngOnInit() {}
}
